[package]
name = "twitch-screenshot-organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "8.0.0"
log = "0.4.25"
env_logger = "0.11.6"
clap = { version = "4.5.26", features = ["derive"] }
